export default {
    "columns":10,
    "image":"_assets_\/anvil.png",
    "imageheight":96,
    "imagewidth":320,
    "margin":0,
    "name":"anvil",
    "spacing":0,
    "tilecount":10,
    "tileheight":96,
    "tilewidth":32,
    "tiles":[
        {
            "animation":[
                {
                    "duration":100,
                    "tileid":0
                },
                {
                    "duration":100,
                    "tileid":1
                },
                {
                    "duration":100,
                    "tileid":2
                },
                {
                    "duration":100,
                    "tileid":3
                },
                {
                    "duration":100,
                    "tileid":4
                },
                {
                    "duration":100,
                    "tileid":5
                },
                {
                    "duration":100,
                    "tileid":6
                },
                {
                    "duration":100,
                    "tileid":7
                },
                {
                    "duration":100,
                    "tileid":8
                },
                {
                    "duration":100,
                    "tileid":9
                }
            ],
            "id":0
        }]
}