export default {
    "columns":26,
    "image":"_assets_\/car.png",
    "imageheight":160,
    "imagewidth":4160,
    "margin":0,
    "name":"car",
    "spacing":0,
    "tilecount":26,
    "tileheight":160,
    "tilewidth":160,
    "tiles":[
        {
            "animation":[
                {
                    "duration":100,
                    "tileid":0
                },
                {
                    "duration":100,
                    "tileid":1
                },
                {
                    "duration":100,
                    "tileid":2
                },
                {
                    "duration":100,
                    "tileid":3
                },
                {
                    "duration":100,
                    "tileid":4
                },
                {
                    "duration":100,
                    "tileid":5
                },
                {
                    "duration":100,
                    "tileid":6
                },
                {
                    "duration":100,
                    "tileid":7
                },
                {
                    "duration":100,
                    "tileid":8
                },
                {
                    "duration":100,
                    "tileid":9
                },
                {
                    "duration":100,
                    "tileid":10
                },
                {
                    "duration":100,
                    "tileid":11
                },
                {
                    "duration":100,
                    "tileid":12
                },
                {
                    "duration":100,
                    "tileid":13
                }
            ],
            "id":0
        }]
}