export default {
    "columns":7,
    "image":"_assets_\/fart.png",
    "imageheight":96,
    "imagewidth":672,
    "margin":0,
    "name":"fart",
    "spacing":0,
    "tilecount":7,
    "tileheight":96,
    "tilewidth":96,
    "tiles":[
        {
            "animation":[
                {
                    "duration":100,
                    "tileid":0
                },
                {
                    "duration":100,
                    "tileid":1
                },
                {
                    "duration":100,
                    "tileid":2
                },
                {
                    "duration":100,
                    "tileid":3
                },
                {
                    "duration":100,
                    "tileid":4
                },
                {
                    "duration":100,
                    "tileid":5
                },
                {
                    "duration":100,
                    "tileid":6
                },
            ],
            "id":0
        }]
}