export default {
    "columns":8,
    "image":"_assets_\/fireball.png",
    "imageheight":64,
    "imagewidth":256,
    "margin":0,
    "name":"fireball",
    "spacing":0,
    "tilecount":8,
    "tileheight":64,
    "tilewidth":32,
    "tiles":[
        {
            "animation":[
                {
                    "duration":100,
                    "tileid":0
                },
                {
                    "duration":100,
                    "tileid":1
                },
                {
                    "duration":100,
                    "tileid":2
                },
                {
                    "duration":100,
                    "tileid":3
                },
                {
                    "duration":100,
                    "tileid":4
                },
                {
                    "duration":100,
                    "tileid":5
                },
                {
                    "duration":100,
                    "tileid":6
                },
                {
                    "duration":100,
                    "tileid":7
                }
            ],
            "id":0
        }]
}