export default {
    "columns":16,
    "image":"_assets_\/lightning.png",
    "imageheight":96,
    "imagewidth":512,
    "margin":0,
    "name":"lightning",
    "spacing":0,
    "tilecount":16,
    "tileheight":96,
    "tilewidth":32,
    "tiles":[
        {
            "animation":[
                {
                    "duration":100,
                    "tileid":0
                },
                {
                    "duration":100,
                    "tileid":1
                },
                {
                    "duration":100,
                    "tileid":2
                },
                {
                    "duration":100,
                    "tileid":3
                },
                {
                    "duration":100,
                    "tileid":4
                },
                {
                    "duration":100,
                    "tileid":5
                },
                {
                    "duration":100,
                    "tileid":6
                },
                {
                    "duration":100,
                    "tileid":7
                },
                {
                    "duration":100,
                    "tileid":8
                },
                {
                    "duration":100,
                    "tileid":9
                },
                {
                    "duration":100,
                    "tileid":10
                },
                {
                    "duration":100,
                    "tileid":11
                },
                {
                    "duration":100,
                    "tileid":12
                },
                {
                    "duration":100,
                    "tileid":13
                },
                {
                    "duration":100,
                    "tileid":14
                },
                {
                    "duration":100,
                    "tileid":15
                }
            ],
            "id":0
        }]
}