export default {
    "columns":10,
    "image":"_assets_\/piano.png",
    "imageheight":128,
    "imagewidth":320,
    "margin":0,
    "name":"piano_tileset",
    "spacing":0,
    "tilecount":10,
    "tileheight":128,
    "tilewidth":32,
    "tiles":[
        {
            "animation":[
                {
                    "duration":100,
                    "tileid":0
                },
                {
                    "duration":100,
                    "tileid":1
                },
                {
                    "duration":100,
                    "tileid":2
                },
                {
                    "duration":100,
                    "tileid":3
                },
                {
                    "duration":100,
                    "tileid":4
                },
                {
                    "duration":100,
                    "tileid":5
                },
                {
                    "duration":100,
                    "tileid":6
                },
                {
                    "duration":100,
                    "tileid":7
                },
                {
                    "duration":100,
                    "tileid":8
                },
                {
                    "duration":100,
                    "tileid":9
                }],
            "id":0
        }
    ]
}