export default {
    "columns":11,
    "image":"_assets_\/punch_machine.png",
    "imageheight":32,
    "imagewidth":704,
    "margin":0,
    "name":"punch_machine",
    "spacing":0,
    "tilecount":11,
    "tileheight":32,
    "tilewidth":64,
    "tiles":[
        {
            "animation":[
                {
                    "duration":100,
                    "tileid":0
                },
                {
                    "duration":100,
                    "tileid":1
                },
                {
                    "duration":100,
                    "tileid":2
                },
                {
                    "duration":100,
                    "tileid":3
                },
                {
                    "duration":100,
                    "tileid":4
                },
                {
                    "duration":100,
                    "tileid":5
                },
                {
                    "duration":100,
                    "tileid":6
                },
                {
                    "duration":100,
                    "tileid":7
                },
                {
                    "duration":100,
                    "tileid":8
                },
                {
                    "duration":100,
                    "tileid":9
                },
                {
                    "duration":100,
                    "tileid":10
                }
            ],
            "id":0
        }]
}